In [1]:
import torch
import torch.nn as nn

# Embeddings

In [77]:
embedding = nn.Embedding(5, 3)

Each index i $\in$ 0 ... 4 will be transformed into a 3-vector.

More precisely: this creates a $5 \times 3$ matrix with random values

In [86]:
embedding.weight

Parameter containing:
tensor([[-1.9462,  0.4058,  0.2216],
        [-0.7918, -0.6220,  0.6955],
        [ 0.2757,  0.0152,  0.0460],
        [ 0.8708,  0.3762, -0.0339],
        [ 1.0533, -0.7088, -0.3261]], requires_grad=True)

In [83]:
input = torch.LongTensor([[1,2,4,4], [4,3,2,0]])

In [84]:
emb = embedding(input)
emb

tensor([[[-0.7918, -0.6220,  0.6955],
         [ 0.2757,  0.0152,  0.0460],
         [ 1.0533, -0.7088, -0.3261],
         [ 1.0533, -0.7088, -0.3261]],

        [[ 1.0533, -0.7088, -0.3261],
         [ 0.8708,  0.3762, -0.0339],
         [ 0.2757,  0.0152,  0.0460],
         [-1.9462,  0.4058,  0.2216]]], grad_fn=<EmbeddingBackward0>)

In [95]:
print(embedding(torch.tensor([0, 2, 4])))

tensor([[-1.9462,  0.4058,  0.2216],
        [ 0.2757,  0.0152,  0.0460],
        [ 1.0533, -0.7088, -0.3261]], grad_fn=<EmbeddingBackward0>)
